// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static OMS.Web.Controllers.AccountController Account = new OMS.Web.Controllers.T4MVC_AccountController();
    public static OMS.Web.Controllers.AdminController Admin = new OMS.Web.Controllers.T4MVC_AdminController();
    public static OMS.Web.Controllers.EmployeeController Employee = new OMS.Web.Controllers.T4MVC_EmployeeController();
    public static OMS.Web.Controllers.HomeController Home = new OMS.Web.Controllers.T4MVC_HomeController();
    public static OMS.Web.Controllers.OrderController Order = new OMS.Web.Controllers.T4MVC_OrderController();
    public static OMS.Web.Controllers.ProductController Product = new OMS.Web.Controllers.T4MVC_ProductController();
    public static OMS.Web.Controllers.RoleController Role = new OMS.Web.Controllers.T4MVC_RoleController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class appscript {
            public const string UrlPath = "~/Scripts/appscript";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string account_index_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/account.index.min.js") ? Url("account.index.min.js") : Url("account.index.js");
            public static readonly string category_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/category.min.js") ? Url("category.min.js") : Url("category.js");
            public static readonly string employee_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/employee.min.js") ? Url("employee.min.js") : Url("employee.js");
            public static readonly string product_index_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/product.index.min.js") ? Url("product.index.min.js") : Url("product.index.js");
            public static readonly string role_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/role.min.js") ? Url("role.min.js") : Url("role.js");
        }
    
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class common {
            public const string UrlPath = "~/Scripts/common";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string common_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/common.min.js") ? Url("common.min.js") : Url("common.js");
            public static readonly string modalLoader_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modalLoader.min.js") ? Url("modalLoader.min.js") : Url("modalLoader.js");
        }
    
        public static readonly string Custom_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Custom.min.js") ? Url("Custom.min.js") : Url("Custom.js");
        public static readonly string init_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/init.min.js") ? Url("init.min.js") : Url("init.js");
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_dataTables_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.dataTables.min.js") ? Url("jquery.dataTables.min.js") : Url("jquery.dataTables.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string materialize_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/materialize.min.js") ? Url("materialize.min.js") : Url("materialize.js");
        public static readonly string materialize_min_js = Url("materialize.min.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string Custom_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Custom.min.css") ? Url("Custom.min.css") : Url("Custom.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Images {
            public const string UrlPath = "~/Content/Images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string background_jpg = Url("background.jpg");
            public static readonly string background1_jpg = Url("background1.jpg");
            public static readonly string background2_jpg = Url("background2.jpg");
            public static readonly string background3_jpg = Url("background3.jpg");
            public static readonly string bg2_jpg = Url("bg2.jpg");
            public static readonly string loader_gif = Url("loader.gif");
            public static readonly string logo_png = Url("logo.png");
            public static readonly string wood_jpg = Url("wood.jpg");
        }
    
        public static readonly string jquery_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.dataTables.min.css") ? Url("jquery.dataTables.min.css") : Url("jquery.dataTables.css");
        public static readonly string materialize_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/materialize.min.css") ? Url("materialize.min.css") : Url("materialize.css");
        public static readonly string materialize_min_css = Url("materialize.min.css");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/style.min.css") ? Url("style.min.css") : Url("style.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class appscript 
            {
                public static class Assets
                {
                    public static readonly string account_index_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/appscript/account.index.js"); 
                    public static readonly string category_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/appscript/category.js"); 
                    public static readonly string employee_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/appscript/employee.js"); 
                    public static readonly string product_index_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/appscript/product.index.js"); 
                    public static readonly string role_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/appscript/role.js"); 
                }
            }
            public static partial class common 
            {
                public static class Assets
                {
                    public static readonly string common_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/common/common.js"); 
                    public static readonly string modalLoader_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/common/modalLoader.js"); 
                }
            }
            public static class Assets
            {
                public static readonly string _references_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/_references.js"); 
                public static readonly string bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.js"); 
                public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.min.js"); 
                public static readonly string Custom_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/Custom.js"); 
                public static readonly string init_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/init.js"); 
                public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.10.2.intellisense.js"); 
                public static readonly string jquery_1_10_2_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.10.2.js"); 
                public static readonly string jquery_1_10_2_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.10.2.min.js"); 
                public static readonly string jquery_dataTables_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.dataTables.js"); 
                public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.js"); 
                public static readonly string jquery_validate_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.min.js"); 
                public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.js"); 
                public static readonly string jquery_validate_unobtrusive_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.min.js"); 
                public static readonly string materialize_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/materialize.js"); 
                public static readonly string materialize_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/materialize.min.js"); 
                public static readonly string modernizr_2_6_2_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/modernizr-2.6.2.js"); 
                public static readonly string respond_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/respond.js"); 
                public static readonly string respond_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/respond.min.js"); 
            }
        }
        public static partial class Content 
        {
            public static partial class Images 
            {
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public static readonly string bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.css");
                public static readonly string bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.min.css");
                public static readonly string Custom_css = T4MVCHelpers.ProcessAssetPath("~/Content/Custom.css");
                public static readonly string jquery_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/jquery.dataTables.css");
                public static readonly string materialize_css = T4MVCHelpers.ProcessAssetPath("~/Content/materialize.css");
                public static readonly string materialize_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/materialize.min.css");
                public static readonly string Site_css = T4MVCHelpers.ProcessAssetPath("~/Content/Site.css");
                public static readonly string style_css = T4MVCHelpers.ProcessAssetPath("~/Content/style.css");
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


